services:
  nginx:
    image: nginx
    container_name: nginx01
    ports:
      - 8080:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
  redis:
    image: redis
    container_name: redis01
    ports:
      - 6379:6379