services:
  nginx:
    image: nginx
    container_name: nginx-1
    ports:
      - 8080:80
    volumes:
      - ${PWD}/index.html:/usr/share/nginx/html/index.html
  redis:
    image: redis
    container_name: redis-1
    ports:
      - 6379:6379