version: '3'

services:

  db:
    image: mysql:8.0-debian
    container_name: mysql-1
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - play-docker-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wp-net

  php-app:
    image: wx/php82-with-xdebug
    build:
      context: .
      dockerfile: ./dockerfile-php
    container_name: php-app
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
      # - 9003:9003
    depends_on:
      - db
    networks:
      - wp-net
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx
    container_name: nginx-php
    ports:
      - 8086:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app
      - db
    networks:
      - wp-net

volumes:
  play-docker-mysql-data:

networks:
  wp-net:
    driver: bridge